package TournamentTracker;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kuba
 */
public class CreateTournament extends javax.swing.JFrame {

    /**
     * Creates new form CreateTournament
     */
    public CreateTournament() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectTeamLabel = new javax.swing.JLabel();
        createTournamentLabel = new javax.swing.JLabel();
        tournamentNameValue = new javax.swing.JTextField();
        teamsLabel = new javax.swing.JLabel();
        selectTeamComboBox = new javax.swing.JComboBox<>();
        createTeamButton = new javax.swing.JButton();
        deleteTeamButton = new javax.swing.JButton();
        tournamentTeamScrollPanel = new javax.swing.JScrollPane();
        tournamentTeamList = new javax.swing.JList<>();
        tournamentNameLabel = new javax.swing.JLabel();
        addTeamButton = new javax.swing.JButton();
        createTournamentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Tournament");

        selectTeamLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        selectTeamLabel.setForeground(new java.awt.Color(51, 153, 255));
        selectTeamLabel.setText("Select Team");

        createTournamentLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        createTournamentLabel.setForeground(new java.awt.Color(51, 153, 255));
        createTournamentLabel.setText("Create Tournament");

        tournamentNameValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tournamentNameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tournamentNameValueActionPerformed(evt);
            }
        });

        teamsLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        teamsLabel.setForeground(new java.awt.Color(51, 153, 255));
        teamsLabel.setText("Teams");

        selectTeamComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectTeamComboBox.setMaximumRowCount(20);
        selectTeamComboBox.setToolTipText("");

        createTeamButton.setText("Create Team");
        createTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTeamButtonActionPerformed(evt);
            }
        });

        deleteTeamButton.setBackground(new java.awt.Color(204, 204, 204));
        deleteTeamButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        deleteTeamButton.setText("Delete Selected");
        deleteTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTeamButtonActionPerformed(evt);
            }
        });

        tournamentTeamList.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tournamentTeamList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "tournamentTeamList" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tournamentTeamList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tournamentTeamScrollPanel.setViewportView(tournamentTeamList);
        tournamentTeamList.getAccessibleContext().setAccessibleName("tournamentTeamList");
        tournamentTeamList.getAccessibleContext().setAccessibleParent(this);

        tournamentNameLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        tournamentNameLabel.setForeground(new java.awt.Color(51, 153, 255));
        tournamentNameLabel.setText("Tournament Name");

        addTeamButton.setBackground(new java.awt.Color(204, 204, 204));
        addTeamButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        addTeamButton.setText("Add Team");
        addTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeamButtonActionPerformed(evt);
            }
        });

        createTournamentButton.setBackground(new java.awt.Color(204, 204, 204));
        createTournamentButton.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        createTournamentButton.setText("Create tournament");
        createTournamentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTournamentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(createTournamentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(selectTeamComboBox, 0, 303, Short.MAX_VALUE)
                                        .addComponent(tournamentNameValue)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(selectTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(35, 35, 35)
                                            .addComponent(createTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(tournamentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(addTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tournamentTeamScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(deleteTeamButton))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addComponent(teamsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(createTournamentButton)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createTournamentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teamsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tournamentTeamScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tournamentNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tournamentNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selectTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createTeamButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectTeamComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteTeamButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createTournamentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        tournamentNameValue.getAccessibleContext().setAccessibleName("tournamentName");
        createTeamButton.getAccessibleContext().setAccessibleName("createTeamButton");
        deleteTeamButton.getAccessibleContext().setAccessibleName("deleteTeamButton");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tournamentNameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tournamentNameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tournamentNameValueActionPerformed

    private void deleteTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTeamButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteTeamButtonActionPerformed

    private void addTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeamButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTeamButtonActionPerformed

    private void createTournamentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTournamentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createTournamentButtonActionPerformed

    private void createTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTeamButtonActionPerformed
        dispose();
        CreateTeam createTeam = new CreateTeam();
        createTeam.setVisible(true);
    }//GEN-LAST:event_createTeamButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTournament.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTournament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addTeamButton;
    public javax.swing.JButton createTeamButton;
    public javax.swing.JButton createTournamentButton;
    private javax.swing.JLabel createTournamentLabel;
    public javax.swing.JButton deleteTeamButton;
    public javax.swing.JComboBox<String> selectTeamComboBox;
    private javax.swing.JLabel selectTeamLabel;
    private javax.swing.JLabel teamsLabel;
    private javax.swing.JLabel tournamentNameLabel;
    public javax.swing.JTextField tournamentNameValue;
    public javax.swing.JList<String> tournamentTeamList;
    private javax.swing.JScrollPane tournamentTeamScrollPanel;
    // End of variables declaration//GEN-END:variables
}
