/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TournamentTracker;

/**
 *
 * @author Kuba
 */
public class CreateTeam extends javax.swing.JFrame {

    /**
     * Creates new form CreateTeam
     */
    public CreateTeam() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createTeamLabel = new javax.swing.JLabel();
        selectTeamMemberLabel = new javax.swing.JLabel();
        teamNameValue = new javax.swing.JTextField();
        selectTeamMemberComboBox = new javax.swing.JComboBox<>();
        addMemberButton = new javax.swing.JButton();
        teamNameLabel = new javax.swing.JLabel();
        createNewMemberPanel = new javax.swing.JPanel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneNumberLabel = new javax.swing.JLabel();
        firstNameValue = new javax.swing.JTextField();
        phoneNumberValue = new javax.swing.JTextField();
        lastNameValue = new javax.swing.JTextField();
        emailValue = new javax.swing.JTextField();
        createMemberButton = new javax.swing.JButton();
        teamMembersScrollPane = new javax.swing.JScrollPane();
        teamMembersList = new javax.swing.JList<>();
        deleteMemberButton = new javax.swing.JButton();
        createTeamButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create team");

        createTeamLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        createTeamLabel.setForeground(new java.awt.Color(51, 153, 255));
        createTeamLabel.setText("Create Team");

        selectTeamMemberLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        selectTeamMemberLabel.setForeground(new java.awt.Color(51, 153, 255));
        selectTeamMemberLabel.setText("Select Team Member");

        teamNameValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamNameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamNameValueActionPerformed(evt);
            }
        });

        selectTeamMemberComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        selectTeamMemberComboBox.setMaximumRowCount(20);
        selectTeamMemberComboBox.setToolTipText("");

        addMemberButton.setBackground(new java.awt.Color(204, 204, 204));
        addMemberButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        addMemberButton.setText("Add Member");
        addMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberButtonActionPerformed(evt);
            }
        });

        teamNameLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        teamNameLabel.setForeground(new java.awt.Color(51, 153, 255));
        teamNameLabel.setText("Team Name");

        createNewMemberPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Create New Member", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 0, 18), new java.awt.Color(51, 153, 255))); // NOI18N

        firstNameLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(51, 153, 255));
        firstNameLabel.setText("First Name");

        lastNameLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(51, 153, 255));
        lastNameLabel.setText("Last Name");

        emailLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(51, 153, 255));
        emailLabel.setText("Email");

        phoneNumberLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        phoneNumberLabel.setForeground(new java.awt.Color(51, 153, 255));
        phoneNumberLabel.setText("Phone number");

        firstNameValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        firstNameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameValueActionPerformed(evt);
            }
        });

        phoneNumberValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneNumberValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberValueActionPerformed(evt);
            }
        });

        lastNameValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastNameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameValueActionPerformed(evt);
            }
        });

        emailValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailValueActionPerformed(evt);
            }
        });

        createMemberButton.setBackground(new java.awt.Color(204, 204, 204));
        createMemberButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        createMemberButton.setText("Create Member");
        createMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createMemberButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createNewMemberPanelLayout = new javax.swing.GroupLayout(createNewMemberPanel);
        createNewMemberPanel.setLayout(createNewMemberPanelLayout);
        createNewMemberPanelLayout.setHorizontalGroup(
            createNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createNewMemberPanelLayout.createSequentialGroup()
                .addGroup(createNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createNewMemberPanelLayout.createSequentialGroup()
                        .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(firstNameValue))
                    .addGroup(createNewMemberPanelLayout.createSequentialGroup()
                        .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameValue))
                    .addGroup(createNewMemberPanelLayout.createSequentialGroup()
                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(emailValue, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                    .addGroup(createNewMemberPanelLayout.createSequentialGroup()
                        .addComponent(phoneNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(phoneNumberValue)))
                .addContainerGap())
            .addGroup(createNewMemberPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(createMemberButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        createNewMemberPanelLayout.setVerticalGroup(
            createNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createNewMemberPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(createNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumberValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(createNewMemberPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        teamMembersList.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        teamMembersList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "teamMembersList" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        teamMembersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        teamMembersScrollPane.setViewportView(teamMembersList);

        deleteMemberButton.setBackground(new java.awt.Color(204, 204, 204));
        deleteMemberButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        deleteMemberButton.setText("Delete Selected");
        deleteMemberButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMemberButtonActionPerformed(evt);
            }
        });

        createTeamButton.setBackground(new java.awt.Color(204, 204, 204));
        createTeamButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        createTeamButton.setText("Create Team");
        createTeamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createTeamButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(addMemberButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(teamNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(createTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createNewMemberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(teamNameValue, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(selectTeamMemberComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 294, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(selectTeamMemberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(teamMembersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(deleteMemberButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(createTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createTeamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(teamNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teamNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectTeamMemberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(selectTeamMemberComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addMemberButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createNewMemberPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(teamMembersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteMemberButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createTeamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        teamNameValue.getAccessibleContext().setAccessibleName("TeamNameValue");
        deleteMemberButton.getAccessibleContext().setAccessibleName("deleteMemberButton");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teamNameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamNameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamNameValueActionPerformed

    private void addMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMemberButtonActionPerformed

    private void firstNameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameValueActionPerformed

    private void phoneNumberValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberValueActionPerformed

    private void lastNameValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameValueActionPerformed

    private void emailValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailValueActionPerformed

    private void createMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createMemberButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createMemberButtonActionPerformed

    private void deleteMemberButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMemberButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMemberButtonActionPerformed

    private void createTeamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createTeamButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createTeamButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateTeam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addMemberButton;
    public javax.swing.JButton createMemberButton;
    private javax.swing.JPanel createNewMemberPanel;
    public javax.swing.JButton createTeamButton;
    private javax.swing.JLabel createTeamLabel;
    public javax.swing.JButton deleteMemberButton;
    private javax.swing.JLabel emailLabel;
    public javax.swing.JTextField emailValue;
    private javax.swing.JLabel firstNameLabel;
    public javax.swing.JTextField firstNameValue;
    private javax.swing.JLabel lastNameLabel;
    public javax.swing.JTextField lastNameValue;
    private javax.swing.JLabel phoneNumberLabel;
    public javax.swing.JTextField phoneNumberValue;
    public javax.swing.JComboBox<String> selectTeamMemberComboBox;
    private javax.swing.JLabel selectTeamMemberLabel;
    public javax.swing.JList<String> teamMembersList;
    private javax.swing.JScrollPane teamMembersScrollPane;
    private javax.swing.JLabel teamNameLabel;
    public javax.swing.JTextField teamNameValue;
    // End of variables declaration//GEN-END:variables
}
