/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TournamentTracker;

/**
 *
 * @author Kuba
 */
public class TournamentStart extends javax.swing.JFrame {

    /**
     * Creates new form TournamentStart
     */
    public TournamentStart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tournamentDashboardLabel = new javax.swing.JLabel();
        loadTournamentLabel = new javax.swing.JLabel();
        loadTournamentComboBox = new javax.swing.JComboBox<>();
        loadTournamentButton = new javax.swing.JButton();
        createNewTournamentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tournamentDashboardLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        tournamentDashboardLabel.setForeground(new java.awt.Color(51, 153, 255));
        tournamentDashboardLabel.setText("Tournament Dashboard");

        loadTournamentLabel.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        loadTournamentLabel.setForeground(new java.awt.Color(51, 153, 255));
        loadTournamentLabel.setText("Load Tournament");

        loadTournamentComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadTournamentComboBox.setMaximumRowCount(20);
        loadTournamentComboBox.setToolTipText("");
        loadTournamentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTournamentComboBoxActionPerformed(evt);
            }
        });

        loadTournamentButton.setBackground(new java.awt.Color(204, 204, 204));
        loadTournamentButton.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        loadTournamentButton.setText("Load Tournament");
        loadTournamentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadTournamentButtonActionPerformed(evt);
            }
        });

        createNewTournamentButton.setBackground(new java.awt.Color(204, 204, 204));
        createNewTournamentButton.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        createNewTournamentButton.setText("Create New Tournament");
        createNewTournamentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewTournamentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(tournamentDashboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(loadTournamentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(createNewTournamentButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(loadTournamentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(loadTournamentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(tournamentDashboardLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadTournamentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(loadTournamentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loadTournamentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createNewTournamentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadTournamentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTournamentComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadTournamentComboBoxActionPerformed

    private void loadTournamentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadTournamentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadTournamentButtonActionPerformed

    private void createNewTournamentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewTournamentButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createNewTournamentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TournamentStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TournamentStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TournamentStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TournamentStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TournamentStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton createNewTournamentButton;
    public javax.swing.JButton loadTournamentButton;
    public javax.swing.JComboBox<String> loadTournamentComboBox;
    private javax.swing.JLabel loadTournamentLabel;
    private javax.swing.JLabel tournamentDashboardLabel;
    // End of variables declaration//GEN-END:variables
}
